# Generated by Django 4.0.4 on 2022-06-17 05:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unwantedInfo', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departmentalInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('PRN_NO', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, default=' ', max_length=50)),
                ('lastname', models.CharField(blank=True, default=' ', max_length=50)),
                ('bio', models.TextField(null=True)),
                ('middelname', models.CharField(blank=True, default=' ', max_length=50)),
                ('birthdate', models.CharField(blank=True, default=' ', max_length=50)),
                ('address', models.CharField(blank=True, default=' ', max_length=50)),
                ('phoneNO', models.CharField(blank=True, default=' ', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('gender', models.CharField(default='M', max_length=7)),
                ('profilePic', models.URLField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png')),
                ('registerDate', models.DateField(auto_now=True)),
                ('countryCode', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unwantedInfo.countrycode')),
                ('departmentId', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='departmentalInfo.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('SocialMediaId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SocialMediaName', models.CharField(max_length=100)),
                ('SocialMediaLink', models.URLField()),
                ('PRN_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='otpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(unique=True)),
                ('createdAt', models.TimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('LanguageId', models.AutoField(primary_key=True, serialize=False)),
                ('LanguageName', models.CharField(max_length=100)),
                ('Level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('PRN_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
