# Generated by Django 4.0.4 on 2022-06-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middelName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('spacalizedIn', models.CharField(max_length=100)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentalInfo.department')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseNo', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentalInfo.department')),
            ],
        ),
    ]
