# Generated by Django 4.0.4 on 2022-04-18 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmentalInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middelName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('spacalizedIn', models.CharField(max_length=100)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentalInfo.department')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('courseNo', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentalInfo.department')),
            ],
        ),
    ]
