# Generated by Django 4.0.4 on 2022-04-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=50)),
                ('CountriesIsoCode', models.CharField(max_length=2)),
                ('CountriesIsdCode', models.CharField(max_length=7)),
            ],
        ),
    ]
