# Generated by Django 4.0.4 on 2022-04-18 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentalInfo', '0002_teachers_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('examNo', models.AutoField(primary_key=True, serialize=False)),
                ('ExamName', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('PRN_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('courseNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentalInfo.courses')),
                ('examtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExaminationInfo.examination')),
            ],
        ),
        migrations.CreateModel(
            name='ConductedOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('courseNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExaminationInfo.exam')),
                ('examNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExaminationInfo.examination')),
            ],
        ),
    ]
