# Generated by Django 4.0.4 on 2022-06-17 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExaminationInfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departmentalInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='PRN_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='courseNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentalInfo.courses'),
        ),
        migrations.AddField(
            model_name='exam',
            name='examtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExaminationInfo.examination'),
        ),
        migrations.AddField(
            model_name='conductedon',
            name='courseNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExaminationInfo.exam'),
        ),
        migrations.AddField(
            model_name='conductedon',
            name='examNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExaminationInfo.examination'),
        ),
    ]
