# Generated by Django 4.0.4 on 2022-06-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentalInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('CertificationNo', models.AutoField(primary_key=True, serialize=False)),
                ('CertificationName', models.CharField(max_length=100)),
                ('DateOfCompletion', models.DateField(blank=True, default=' ')),
                ('ExpaireDate', models.DateField(blank=True, default=' ')),
                ('CerificateIdNo', models.IntegerField(blank=True, default=' ', unique=True)),
                ('Certificate', models.URLField(blank=True, default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('GoalId', models.AutoField(primary_key=True, serialize=False)),
                ('GoalName', models.CharField(max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True, default=' ')),
                ('attachment', models.URLField(blank=True, default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Intranship',
            fields=[
                ('IntranshipId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('DateOfJoin', models.DateField()),
                ('Duration', models.IntegerField()),
                ('EndingDate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('MailstonesId', models.AutoField(primary_key=True, serialize=False)),
                ('MailstoneName', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAcheivement',
            fields=[
                ('AcheivementId', models.AutoField(primary_key=True, serialize=False)),
                ('AcheivementName', models.CharField(max_length=100)),
                ('AcadamicYear', models.IntegerField()),
                ('Details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('StartDate', models.DateField()),
                ('Duration', models.IntegerField(blank=True, default=' ')),
                ('status', models.BooleanField(default=0)),
                ('CourseNo', models.ForeignKey(blank=True, default=' ', on_delete=django.db.models.deletion.CASCADE, to='departmentalInfo.courses')),
            ],
        ),
    ]
