# Generated by Django 4.0.4 on 2022-04-18 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentalInfo', '0002_teachers_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('CertificationNo', models.AutoField(primary_key=True, serialize=False)),
                ('CertificationName', models.CharField(max_length=100)),
                ('DateOfCompletion', models.DateField()),
                ('ExpaireDate', models.DateField()),
                ('CerificateIdNo', models.IntegerField(unique=True)),
                ('Certificate', models.URLField(blank=True, default=' ')),
                ('PRN_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('GoalId', models.AutoField(primary_key=True, serialize=False)),
                ('GoalName', models.CharField(max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('PRN_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('status', models.BooleanField(default=0)),
                ('CourseNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentalInfo.courses')),
                ('PRN_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAcheivement',
            fields=[
                ('AcheivementId', models.AutoField(primary_key=True, serialize=False)),
                ('AcheivementName', models.CharField(max_length=100)),
                ('StartingDate', models.DateField()),
                ('EndingDate', models.DateField()),
                ('AcadamicYear', models.IntegerField()),
                ('Details', models.CharField(max_length=500)),
                ('PRN_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('MailstonesId', models.AutoField(primary_key=True, serialize=False)),
                ('MailstoneName', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=0)),
                ('AcheivementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.personalacheivement')),
                ('CertificationNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.certifications')),
                ('PRN_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.goals')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.personalproject')),
            ],
        ),
        migrations.CreateModel(
            name='Intranship',
            fields=[
                ('IntranshipId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('DateOfJoin', models.DateField()),
                ('Duration', models.IntegerField()),
                ('EndingDate', models.IntegerField()),
                ('ComplitionCertificate', models.URLField()),
                ('PRN_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
