# Generated by Django 4.0.4 on 2022-06-17 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievementalInfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalproject',
            name='PRN_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalacheivement',
            name='Attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.certifications'),
        ),
        migrations.AddField(
            model_name='personalacheivement',
            name='PRN_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestones',
            name='AcheivementId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.personalacheivement'),
        ),
        migrations.AddField(
            model_name='milestones',
            name='CertificationNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.certifications'),
        ),
        migrations.AddField(
            model_name='milestones',
            name='PRN_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestones',
            name='goalId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.goals'),
        ),
        migrations.AddField(
            model_name='milestones',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.personalproject'),
        ),
        migrations.AddField(
            model_name='intranship',
            name='ComplitionCertificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievementalInfo.certifications'),
        ),
        migrations.AddField(
            model_name='intranship',
            name='PRN_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goals',
            name='PRN_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certifications',
            name='PRN_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
